# Docker builder image naming
BUILDER_NAME="w1700k-autobuild"
BUILDER_TAG="autobuild"

# Build from rchen14b's openwrt fork, w1700k_autobuild branch
REPO_URL="https://github.com/rchen14b/openwrt_rchen14b"
REPO_BRANCH="w1700k_autobuild"
